//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSystemUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExtendedEnums {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtendedEnums() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameSystemUI.Resources.ExtendedEnums", typeof(ExtendedEnums).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能宿主未找到.
        /// </summary>
        internal static string Description_GameSystemUI_AbilitySystemUI_ECmdErrorAbility_AbilityHostNotFound {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.AbilitySystemUI.ECmdErrorAbility.AbilityHostNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 技能充能层数不足.
        /// </summary>
        internal static string Description_GameSystemUI_AbilitySystemUI_ECmdErrorAbility_ChargeIsNotEnough {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.AbilitySystemUI.ECmdErrorAbility.ChargeIsNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_Advanced_EDefaultItemCategory_All {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.Advanced.EDefaultItemCategory.All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试分类1.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_Advanced_EMyItemCategory_Test1 {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.Advanced.EMyItemCategory.Test1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试分类2.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_Advanced_EMyItemCategory_Test2 {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.Advanced.EMyItemCategory.Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 测试分类3.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_Advanced_EMyItemCategory_Test3 {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.Advanced.EMyItemCategory.Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 找不到满足条件的格子.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_ECmdErrorInventory_AssignableSlotNotFound {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.ECmdErrorInventory.AssignableSlotNotFoun" +
                        "d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物品所有者为空.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_ECmdErrorInventory_ItemCarrierNotFound {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.ECmdErrorInventory.ItemCarrierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 物品格子UI为空.
        /// </summary>
        internal static string Description_GameSystemUI_GameInventoryUI_ECmdErrorInventory_SlotUINotFound {
            get {
                return ResourceManager.GetString("Description_GameSystemUI.GameInventoryUI.ECmdErrorInventory.SlotUINotFound", resourceCulture);
            }
        }
    }
}
